### ISSUE TITLE
beforeFilter and afterFilter are missing from the search

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs-pro#13]
`beforeFilter `and `afterFilter `are missing from the search, however, both are visible on the [hooks list](https://docs.handsontable.com/pro/1.14.2/Hooks.html).

**Comment by randy-argonillo** [comment]
beforeFilter and afterFilter are no longer in the hooks list. Have these two hooks deprecated?

**Comment by AMBudnik** [comment]
No @randy-argonillo it's only a bug. They will return to the list.

**Comment by budnix** [comment]
Thanks, @AMBudnik for reporting this bug. I've deployed fixed version. Missing hooks are now shown correctly.

**Comment by AMBudnik** [comment]
Thanks @budnix !
