### ISSUE TITLE
Wrong comment for range (Export plugin)

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs-pro#7]
at https://docs.handsontable.com/pro/1.7.4/demo-export-file.html we're writing that the arguments for `range` option are:

`[startRow, endRow, startColumn, endColumn]`

while it's

`[startRow, startColumn, endRow, endColumn]`

example: http://jsfiddle.net/28kus5n5/

**Comment by primaryobjects** [comment]
I've confirmed the same issue. See also https://github.com/handsontable/docs-pro/pull/12 and https://github.com/handsontable/docs-pro/pull/17

**Comment by AMBudnik** [comment]
Thank you for bounding the topics.

**Comment by wszymanski** [comment]
Fixed.
