### ISSUE TITLE
search options isn't available via menu

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/docs-pro#9]
As reported at https://github.com/handsontable/handsontable/issues/4076

When we click the `search` we do not get it in the viewport.

![example3](https://cloud.githubusercontent.com/assets/10757813/23013002/11db44d2-f429-11e6-9eff-c75651b56377.gif)

**Comment by AMBudnik** [comment]
it's still an issue.

**Comment by swistach** [comment]
Our search input has the same id.
![screen shot 2018-07-06 at 13 57 30](https://user-images.githubusercontent.com/11849621/42377683-916d7902-8124-11e8-8024-727172f55eb0.png)

**Comment by AMBudnik** [comment]
The issue is no longer replicable in v 5.0.1
